import {get} from '../infra/utils';

const countries = [
  {
    name: 'Afghanistan',
    synonyms: ['Afghan'],
    alpha2: 'af',
    countryCode: 4,
    nationality: 'Afghan',
    translations: {he: 'אפגניסטן', fr: 'Afghanistan', es: 'Afganistán'},
    pluralNation: {en: 'Afghans', he: 'אפגנים', fr: 'Afghans', es: 'Afganos'},
  },
  {
    name: 'Åland Islands',
    synonyms: [],
    alpha2: 'ax',
    countryCode: 248,
    nationality: 'Åland Island',
    translations: {he: 'אולנד', fr: '', es: ''},
    pluralNation: {en: 'Åland Islands', he: 'אולנדים', es: 'suecos'},
  },
  {
    name: 'Albania',
    synonyms: [],
    alpha2: 'al',
    countryCode: 8,
    nationality: 'Albanian',
    translations: {he: 'אלבניה', fr: 'Albanie', es: 'Albania'},
    pluralNation: {
      en: 'Albanians',
      he: 'אלבנים',
      fr: 'Albanais',
      es: 'albanos',
    },
  },
  {
    name: 'Algeria',
    synonyms: ['אלג׳יר'],
    alpha2: 'dz',
    countryCode: 12,
    nationality: 'Algerian',
    translations: {he: 'אלג׳יריה', fr: 'Algérie', es: 'Argelia'},
    pluralNation: {
      en: 'Algerians',
      he: 'אלג׳יראים',
      fr: 'Algériens',
      es: 'argelios',
    },
  },
  {
    name: 'American Samoa',
    synonyms: [],
    alpha2: 'as',
    countryCode: 16,
    nationality: 'American Samoan',
    translations: {he: 'סמואה האמריקנית', fr: '', es: ''},
    pluralNation: {es: 'samoanos'},
  },
  {
    name: 'Andorra',
    synonyms: [],
    alpha2: 'ad',
    countryCode: 20,
    nationality: 'Andorran',
    translations: {he: 'אנדורה', fr: 'Andorre', es: 'Andorra'},
    pluralNation: {
      en: 'Andorrans',
      he: 'אנדוראים',
      fr: 'Andorrans',
      es: 'andorranos',
    },
  },
  {
    name: 'Angola',
    synonyms: [],
    alpha2: 'ao',
    countryCode: 24,
    nationality: 'Angolan',
    translations: {he: 'אנגולה', fr: 'Angola', es: 'Angola'},
    pluralNation: {
      en: 'Angolan',
      he: 'אנגולים',
      fr: 'Angolais',
      es: 'Angoleños',
    },
  },
  {
    name: 'Anguilla',
    synonyms: [],
    alpha2: 'ai',
    countryCode: 660,
    nationality: 'Anguillan',
    translations: {he: 'אנגילה', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Antarctica',
    synonyms: [],
    alpha2: 'aq',
    countryCode: 10,
    nationality: 'Antarctic',
    translations: {he: 'אנטארקטיקה', fr: '', es: ''},
    pluralNation: {en: 'Antarctica'},
  },
  {
    name: 'Antigua and Barbuda',
    synonyms: [],
    alpha2: 'ag',
    countryCode: 28,
    nationality: 'Antiguan or Barbudan',
    translations: {
      he: 'אנטיגואה',
      fr: 'Antigua-et-Barbuda',
      es: 'Antigua y Barbuda',
    },
    pluralNation: {
      he: 'אנטיגואנים',
      fr: 'Antiguais et Barbudiens',
      es: 'antiguanos',
    },
  },
  {
    name: 'Argentina',
    synonyms: ['Arg', 'República Argentina'],
    alpha2: 'ar',
    countryCode: 32,
    nationality: 'Argentine',
    translations: {he: 'ארגנטינה', fr: 'Argentine', es: 'Argentina'},
    pluralNation: {
      en: 'Argentinians',
      he: 'ארגנטינאים',
      fr: 'Argentins',
      es: 'argentinos',
    },
  },
  {
    name: 'Armenia',
    synonyms: [],
    alpha2: 'am',
    countryCode: 51,
    nationality: 'Armenian',
    translations: {he: 'ארמניה', fr: 'Arménie', es: 'Armenia'},
    pluralNation: {
      en: 'Armenians',
      he: 'ארמנים',
      fr: 'Arméniens',
      es: 'armenios',
    },
  },
  {
    name: 'Aruba',
    synonyms: [],
    alpha2: 'aw',
    countryCode: 533,
    nationality: 'Aruban',
    translations: {he: 'ארובה', fr: '', es: ''},
    pluralNation: {en: 'Arubans', he: 'ארובים', es: 'arubanos'},
  },
  {
    name: 'Australia',
    synonyms: [],
    alpha2: 'au',
    countryCode: 36,
    nationality: 'Australian',
    translations: {he: 'אוסטרליה', fr: 'Australie', es: 'Australia'},
    pluralNation: {
      en: 'Australians',
      he: 'אוסטרלים',
      fr: 'Australiens',
      es: 'australianos',
    },
  },
  {
    name: 'Austria',
    isGDPR: true,
    synonyms: [],
    alpha2: 'at',
    countryCode: 40,
    nationality: 'Austrian',
    translations: {he: 'אוסטריה', fr: 'Autriche', es: 'Austria'},
    pluralNation: {
      en: 'Austrian',
      he: 'אוסטרים',
      fr: 'Autrichiens',
      es: 'austriacos',
    },
  },
  {
    name: 'Azerbaijan',
    synonyms: [],
    alpha2: 'az',
    countryCode: 31,
    nationality: 'Azerbaijani, Azeri',
    translations: {he: 'אזרבייג׳ן', fr: 'Azerbaïdjan', es: 'Azerbaiyán'},
    pluralNation: {
      en: 'Azerbaijanis',
      he: 'אזרבייג׳נים',
      fr: 'Azerbaïdjanais',
      es: 'azerbaiyanos',
    },
  },
  {
    name: 'Bahamas',
    synonyms: [],
    alpha2: 'bs',
    countryCode: 44,
    nationality: 'Bahamian',
    translations: {he: 'בהמאס', fr: 'Bahamas', es: 'Bahamas'},
    pluralNation: {
      en: 'Bahamians',
      he: 'ילידי בהמאס',
      fr: 'Bahamiens',
      es: 'bahameños\nbahameses',
    },
  },
  {
    name: 'Bahrain',
    synonyms: [],
    alpha2: 'bh',
    countryCode: 48,
    nationality: 'Bahraini',
    translations: {he: 'בחריין', fr: 'Bahreïn', es: 'Bahrein'},
    pluralNation: {en: 'Bahrainis', fr: 'Bahreïnis', es: 'bareiní'},
  },
  {
    name: 'Bangladesh',
    synonyms: [],
    alpha2: 'bd',
    countryCode: 50,
    nationality: 'Bangladeshi',
    translations: {he: 'בנגלדש', fr: 'Bangladesh', es: 'Bangladesh'},
    pluralNation: {
      en: 'Bangladeshis',
      he: 'בנגלדשים',
      fr: 'Bangladais',
      es: 'Bangladesís',
    },
  },
  {
    name: 'Barbados',
    synonyms: [],
    alpha2: 'bb',
    countryCode: 52,
    nationality: 'Barbadian',
    translations: {he: 'ברבדוס', fr: 'Barbade', es: 'Barbados'},
    pluralNation: {
      en: 'Barbadians',
      he: 'ברבדוסים',
      fr: 'Barbadiens',
      es: 'Barbadenses',
    },
  },
  {
    name: 'Belarus',
    synonyms: ['בלרוסיה'],
    alpha2: 'by',
    countryCode: 112,
    nationality: 'Belarusian',
    translations: {he: 'בלרוס', fr: 'Bélarus', es: 'Belarús'},
    pluralNation: {
      en: 'Belarusians',
      he: 'בלרוסים',
      fr: 'Biélorusses',
      es: 'Bielorrusos',
    },
  },
  {
    name: 'Belgium',
    isGDPR: true,
    synonyms: [],
    alpha2: 'be',
    countryCode: 56,
    nationality: 'Belgian',
    translations: {he: 'בלגיה', fr: 'Belgique', es: 'Bélgica'},
    pluralNation: {en: 'Belgians', he: 'בלגים', fr: 'Belges', es: 'belgas'},
  },
  {
    name: 'Belize',
    synonyms: [],
    alpha2: 'bz',
    countryCode: 84,
    nationality: 'Belizean',
    translations: {he: 'בליז', fr: 'Belize', es: 'Belice'},
    pluralNation: {
      en: 'Belizians',
      he: 'בליזים',
      fr: 'Béliziens',
      es: 'beliceños',
    },
  },
  {
    name: 'Benin',
    synonyms: [],
    alpha2: 'bj',
    countryCode: 204,
    nationality: 'Beninese, Beninois',
    translations: {he: 'בנין', fr: 'Bénin', es: 'Benin'},
    pluralNation: {en: 'Beninese', fr: 'Béninois', es: 'Beninéses'},
  },
  {
    name: 'Bermuda',
    synonyms: [],
    alpha2: 'bm',
    countryCode: 60,
    nationality: 'Bermudian, Bermudan',
    translations: {he: 'ברמודה', fr: '', es: ''},
    pluralNation: {en: 'Bermudians', he: 'ברמודאים', es: 'bermudeños'},
  },
  {
    name: 'Bhutan',
    synonyms: [],
    alpha2: 'bt',
    countryCode: 64,
    nationality: 'Bhutanese',
    translations: {he: 'בהוטן', fr: 'Bhoutan', es: 'Bhután'},
    pluralNation: {
      en: 'Bhutanese',
      he: 'בהוטנים',
      fr: 'Bhoutanais',
      es: 'butanéses',
    },
  },
  {
    name: 'Bolivia',
    synonyms: ['Estado Plurinacional de Bolivia', 'Bol'],
    alpha2: 'bo',
    countryCode: 68,
    nationality: 'Bolivian',
    translations: {
      he: 'בוליביה',
      fr: 'Bolivie (État plurinational de)',
      es: 'Bolivia (Estado Plurinacional de)',
    },
    pluralNation: {
      en: 'Bolivians',
      he: 'בוליביאנים',
      fr: 'Boliviens',
      es: 'Bolivianos',
    },
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    synonyms: [],
    alpha2: 'bq',
    countryCode: 535,
    nationality: 'Bonaire',
    translations: {he: 'בונייר', fr: '', es: ''},
    pluralNation: {en: 'Bonaires', es: 'Bonairenses'},
  },
  {
    name: 'Bosnia and Herzegovina',
    synonyms: [],
    alpha2: 'ba',
    countryCode: 70,
    nationality: 'Bosnian or Herzegovinian',
    translations: {
      he: 'בוסניה',
      fr: 'Bosnie-Herzégovine',
      es: 'Bosnia y Herzegovina',
    },
    pluralNation: {en: 'Bosnians', he: 'בוסנים', fr: 'Bosniens', es: 'Bosnios'},
  },
  {
    name: 'Botswana',
    synonyms: ['Tswana'],
    alpha2: 'bw',
    countryCode: 72,
    nationality: 'Motswana, Botswanan',
    translations: {he: 'בוטסואנה', fr: 'Botswana', es: 'Botswana'},
    pluralNation: {en: 'Botswanans', fr: 'Botswanais', es: 'botsuanos'},
  },
  {
    name: 'Bouvet Island',
    synonyms: [],
    alpha2: 'bv',
    countryCode: 74,
    nationality: 'Bouvet Island',
    translations: {he: 'איי בווט', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Brazil',
    synonyms: [],
    alpha2: 'br',
    countryCode: 76,
    nationality: 'Brazilian',
    translations: {he: 'ברזיל', fr: 'Brésil', es: 'Brasil'},
    pluralNation: {
      en: 'Brazilans',
      he: 'ברזילאים',
      fr: 'Brésiliens',
      es: 'brazileños',
    },
  },
  {
    name: 'British Indian',
    synonyms: [],
    alpha2: 'io',
    countryCode: 86,
    nationality: 'BIOT',
    translations: {he: 'הראג׳ הבריטי', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Brunei Darussalam',
    synonyms: ['Brunei'],
    alpha2: 'bn',
    countryCode: 96,
    nationality: 'Bruneian',
    translations: {
      he: 'ברוניי דארוסלאם',
      fr: 'Brunéi Darussalam',
      es: 'Brunei Darussalam',
    },
    pluralNation: {en: 'Bruneians', fr: 'Brunéiens', es: 'bruneanos'},
  },
  {
    name: 'Bulgaria',
    isGDPR: true,
    synonyms: [],
    alpha2: 'bg',
    countryCode: 100,
    nationality: 'Bulgarian',
    translations: {he: 'בולגריה', fr: 'Bulgarie', es: 'Bulgaria'},
    pluralNation: {
      en: 'Bulgarians',
      he: 'בולגרים',
      fr: 'Bulgares',
      es: 'bulgaros',
    },
  },
  {
    name: 'Burkina Faso',
    synonyms: [],
    alpha2: 'bf',
    countryCode: 854,
    nationality: 'Burkinabé',
    translations: {he: 'בורקינה פאסו', fr: '', es: ''},
    pluralNation: {en: 'Burkinese', fr: 'Burkinabés', es: 'Burkinéss'},
  },
  {
    name: 'Burundi',
    synonyms: [],
    alpha2: 'bi',
    countryCode: 108,
    nationality: 'Burundian',
    translations: {he: 'בורונדי', fr: '', es: ''},
    pluralNation: {en: 'Burundians', fr: 'Burundais'},
  },
  {
    name: 'Cabo Verde',
    synonyms: [],
    alpha2: 'cv',
    countryCode: 132,
    nationality: 'Cabo Verdean',
    translations: {he: 'כף ורדה', fr: '', es: ''},
    pluralNation: {en: 'Cabo Verdeans', fr: 'Capverdiens', es: 'caboverdianos'},
  },
  {
    name: 'Cambodia',
    synonyms: [],
    alpha2: 'kh',
    countryCode: 116,
    nationality: 'Cambodian',
    translations: {he: 'קמבודיה', fr: 'Cambodge', es: 'Camboya'},
    pluralNation: {
      en: 'Cambodians',
      he: 'קמבודים',
      fr: 'Cambodgiens',
      es: 'camboyanos',
    },
  },
  {
    name: 'Cameroon',
    synonyms: [],
    alpha2: 'cm',
    countryCode: 120,
    nationality: 'Cameroonian',
    translations: {he: 'קמרון', fr: 'Cameroun', es: 'Camerún'},
    pluralNation: {
      en: 'Cameroonians',
      he: 'קמרונים',
      fr: 'Camerounais',
      es: 'Camerunéses',
    },
  },
  {
    name: 'Canada',
    synonyms: [],
    alpha2: 'ca',
    countryCode: 124,
    nationality: 'Canadian',
    translations: {he: 'קנדה', fr: '', es: 'Canadá'},
    pluralNation: {
      en: 'Canadians',
      he: 'קנדים',
      fr: 'Canadiens',
      es: 'canadienses',
    },
  },
  {
    name: 'Cayman Islands',
    synonyms: [],
    alpha2: 'ky',
    countryCode: 136,
    nationality: 'Caymanian',
    translations: {he: 'איי קיימן', fr: '', es: ''},
    pluralNation: {en: 'Cayman Islands', es: 'caimanéses'},
  },
  {
    name: 'Central African Republic',
    synonyms: ['Centrafrique'],
    alpha2: 'cf',
    countryCode: 140,
    nationality: 'Central African',
    translations: {
      he: 'הרפובליקה המרכז אפריקאית',
      fr: 'République centrafricaine',
      es: 'República Centroafricana',
    },
    pluralNation: {
      en: 'Central Africans',
      fr: 'Centrafricains',
      es: 'Centroafricanos',
    },
  },
  {
    name: 'Chad',
    synonyms: [],
    alpha2: 'td',
    countryCode: 148,
    nationality: 'Chadian',
    translations: {he: 'צ׳אד', fr: 'Tchad', es: ''},
    pluralNation: {
      en: 'Chadians',
      he: 'צ׳אדים',
      fr: 'Tchadiens',
      es: 'Chadianos',
    },
  },
  {
    name: 'Chile',
    synonyms: ['Republica de Chile', 'Chi'],
    alpha2: 'cl',
    countryCode: 152,
    nationality: 'Chilean',
    translations: {he: 'צ׳ילה', fr: 'Chili', es: ''},
    pluralNation: {
      en: 'Chileans',
      he: 'צ׳יליאנים',
      fr: 'Chiliens',
      es: 'Chilenos',
    },
  },
  {
    name: 'China',
    synonyms: ['Chinese', 'chin'],
    alpha2: 'cn',
    countryCode: 156,
    nationality: 'Chinese',
    translations: {he: 'סין', fr: 'Chine', es: ''},
    pluralNation: {en: 'Chinese', he: 'סינים', fr: 'Chinois', es: 'Chinos'},
  },
  {
    name: 'Christmas Island',
    synonyms: [],
    alpha2: 'cx',
    countryCode: 162,
    nationality: 'Christmas Island',
    translations: {he: 'אי חג המולד', fr: '', es: ''},
    pluralNation: {en: 'Christmas Islanders'},
  },
  {
    name: 'Cocos (Keeling) Islands',
    synonyms: [],
    alpha2: 'cc',
    countryCode: 166,
    nationality: 'Cocos Island',
    translations: {he: 'איי קוקוס', fr: '', es: ''},
    pluralNation: {en: 'Cocos (Keeling) Islanders'},
  },
  {
    name: 'Colombia',
    synonyms: ['Co', 'COL', 'Republica de Colombia'],
    alpha2: 'co',
    countryCode: 170,
    nationality: 'Colombian',
    translations: {he: 'קולומביה', fr: 'Colombie', es: ''},
    pluralNation: {
      en: 'Colombians',
      he: 'קולומביאנים',
      fr: 'Colombiens',
      es: 'colombianos',
    },
  },
  {
    name: 'Comoros',
    synonyms: [],
    alpha2: 'km',
    countryCode: 174,
    nationality: 'Comoran, Comorian',
    translations: {he: 'קומורוס', fr: 'Comores', es: 'Comoras'},
    pluralNation: {fr: 'Comoriens'},
  },
  {
    name: 'Republic of the Congo',
    synonyms: ['RDC', 'Congo-Brazzaville'],
    alpha2: 'cg',
    countryCode: 178,
    nationality: 'Congolese',
    translations: {he: 'קונגו', fr: '', es: ''},
    pluralNation: {
      en: 'Congolese',
      he: 'קונגולזים',
      fr: 'Congolais',
      es: 'congoleños',
    },
  },
  {
    name: 'Cook Islands',
    synonyms: [],
    alpha2: 'ck',
    countryCode: 184,
    nationality: 'Cook Island',
    translations: {he: 'איי קוק', fr: '', es: ''},
    pluralNation: {es: 'Cookianos'},
  },
  {
    name: 'Costa Rica',
    synonyms: ['costa rico', 'CR', 'República de Costa Rica'],
    alpha2: 'cr',
    countryCode: 188,
    nationality: 'Costa Rican',
    translations: {he: 'קוסטה ריקה', fr: '', es: ''},
    pluralNation: {
      en: 'Costa Ricans',
      he: 'קוסטו ריקנים',
      fr: 'Costariciens',
      es: 'ticos',
    },
  },
  {
    name: "Côte d'Ivoire",
    synonyms: [],
    alpha2: 'ci',
    countryCode: 384,
    nationality: 'Ivorian',
    translations: {he: 'חוף השנהב', fr: '', es: ''},
    pluralNation: {fr: 'Ivoiriens'},
  },
  {
    name: 'Croatia',
    isGDPR: true,
    synonyms: [],
    alpha2: 'hr',
    countryCode: 191,
    nationality: 'Croatian',
    translations: {he: 'קרואטיה', fr: 'Croatie', es: 'Croacia'},
    pluralNation: {
      en: 'Croatians',
      he: 'קרואטים',
      fr: 'Croates',
      es: 'croatas',
    },
  },
  {
    name: 'Cuba',
    synonyms: ['República de Cuba', 'Cub'],
    alpha2: 'cu',
    countryCode: 192,
    nationality: 'Cuban',
    translations: {he: 'קובה', fr: '', es: ''},
    pluralNation: {en: 'Cubans', he: 'קובנים', fr: 'Cubains', es: 'cubanos'},
  },
  {
    name: 'Curaçao',
    synonyms: [],
    alpha2: 'cw',
    countryCode: 531,
    nationality: 'Curaçaoan',
    translations: {he: 'קוראסאו', fr: '', es: ''},
    pluralNation: {es: 'Curazoleños'},
  },
  {
    name: 'Cyprus',
    isGDPR: true,
    synonyms: [],
    alpha2: 'cy',
    countryCode: 196,
    nationality: 'Cypriot',
    translations: {he: 'קפריסין', fr: 'Chypre', es: 'Chipre'},
    pluralNation: {
      en: 'Cypriots',
      he: 'קפריסאים',
      fr: 'Chypriotes',
      es: 'chipriotas',
    },
  },
  {
    name: 'Czechia',
    isGDPR: true,
    synonyms: ['République tchèque'],
    alpha2: 'cz',
    countryCode: 203,
    nationality: 'Czech',
    translations: {he: 'צ׳כיה', fr: 'Tchéquie', es: 'Chequia'},
    pluralNation: {en: 'Czechs', he: 'צ׳כים', fr: 'Tchèques', es: 'checos'},
  },
  {
    name: 'Denmark',
    isGDPR: true,
    synonyms: ['dane'],
    alpha2: 'dk',
    countryCode: 208,
    nationality: 'Danish',
    translations: {he: 'דנמרק', fr: 'Danemark', es: 'Dinamarca'},
    pluralNation: {en: 'Danish', he: 'דנים', fr: 'Danois', es: 'Danéses'},
  },
  {
    name: 'Djibouti',
    synonyms: [],
    alpha2: 'dj',
    countryCode: 262,
    nationality: 'Djiboutian',
    translations: {he: 'ג׳יבוטי', fr: '', es: ''},
    pluralNation: {en: 'Djiboutians', fr: 'Djiboutiens', es: 'yibutianos'},
  },
  {
    name: 'Dominica',
    synonyms: [],
    alpha2: 'dm',
    countryCode: 212,
    nationality: 'Dominican',
    translations: {he: 'דומיניק', fr: 'Dominique', es: ''},
    pluralNation: {en: 'Dominicans', fr: 'Dominiquais', es: 'Dominiquéses'},
  },
  {
    name: 'Dominican Republic',
    synonyms: ['פונטה קאנה', 'RD', 'dominicana'],
    alpha2: 'do',
    countryCode: 214,
    nationality: 'Dominican',
    translations: {
      he: 'הרפובליקה הדומיניקנית',
      fr: 'République dominicaine',
      es: 'República Dominicana',
    },
    pluralNation: {
      en: 'Dominicans',
      he: 'דומיניקנים',
      fr: 'Dominicains',
      es: 'dominicanos',
    },
  },
  {
    name: 'Ecuador',
    synonyms: ['Rep. de Ecuador', 'Ecu'],
    alpha2: 'ec',
    countryCode: 218,
    nationality: 'Ecuadorian',
    translations: {he: 'אקוודור', fr: 'Équateur', es: ''},
    pluralNation: {
      en: 'Ecuadoreans',
      he: 'אקוודורים',
      fr: 'Équatoriens',
      es: 'ecuatorianos',
    },
  },
  {
    name: 'Egypt',
    synonyms: ['Cairo'],
    alpha2: 'eg',
    countryCode: 818,
    nationality: 'Egyptian',
    translations: {he: 'מצריים', fr: 'Égypte', es: 'Egipto'},
    pluralNation: {
      en: 'Egyptians',
      he: 'מיצרים',
      fr: 'Égyptiens',
      es: 'egipcios',
    },
  },
  {
    name: 'El Salvador',
    synonyms: [
      'Central America',
      'República del Salvador',
      'Rep. del Salvador',
    ],
    alpha2: 'sv',
    countryCode: 222,
    nationality: 'Salvadoran',
    translations: {he: 'סלבדור', fr: '', es: ''},
    pluralNation: {
      en: 'Salvadoreans',
      he: 'סלבדורים',
      fr: 'Salvadoriens',
      es: 'salvadoreños',
    },
  },
  {
    name: 'Equatorial Guinea',
    synonyms: [],
    alpha2: 'gq',
    countryCode: 226,
    nationality: 'Equatorial Guinean, Equatoguinean',
    translations: {
      he: 'גינאה המשוונית',
      fr: 'Guinée équatoriale',
      es: 'Guinea Ecuatorial',
    },
    pluralNation: {fr: 'Équatoguinéens', es: 'Ecuatoguineanos'},
  },
  {
    name: 'Eritrea',
    synonyms: ['northeast Africa'],
    alpha2: 'er',
    countryCode: 232,
    nationality: 'Eritrean',
    translations: {he: 'אריתראה', fr: 'Érythrée', es: 'Eritrea'},
    pluralNation: {
      en: 'Eritreans',
      he: 'אריתראים',
      fr: 'Érythréens',
      es: 'Eritreos',
    },
  },
  {
    name: 'Estonia',
    isGDPR: true,
    synonyms: [],
    alpha2: 'ee',
    countryCode: 233,
    nationality: 'Estonian',
    translations: {he: 'אסתוניה', fr: 'Estonie', es: ''},
    pluralNation: {
      en: 'Estonians',
      he: 'אסתונים',
      fr: 'Estoniens',
      es: 'Estonianos',
    },
  },
  {
    name: 'Ethiopia',
    synonyms: [],
    alpha2: 'et',
    countryCode: 231,
    nationality: 'Ethiopian',
    translations: {he: 'אתיופיה', fr: 'Éthiopie', es: 'Etiopía'},
    pluralNation: {
      en: 'Ethiopians',
      he: 'אתיופים',
      fr: 'Éthiopiens',
      es: 'etiopes',
    },
  },
  {
    name: 'Falkland Islands (Malvinas)',
    synonyms: [],
    alpha2: 'fk',
    countryCode: 238,
    nationality: 'Falkland Island',
    translations: {he: 'איי פוקלנד', fr: '', es: ''},
    pluralNation: {he: 'ילידי האי'},
  },
  {
    name: 'Faroe Islands',
    synonyms: [],
    alpha2: 'fo',
    countryCode: 234,
    nationality: 'Faroese',
    translations: {he: 'איי פארו', fr: '', es: ''},
    pluralNation: {he: 'ילידי האי'},
  },
  {
    name: 'Fiji',
    synonyms: [],
    alpha2: 'fj',
    countryCode: 242,
    nationality: 'Fijian',
    translations: {he: 'פיג׳י', fr: 'Fidji', es: ''},
    pluralNation: {en: 'Fijians', he: 'פיג׳ים', fr: 'Fidjiens', es: 'fiyianos'},
  },
  {
    name: 'Finland',
    isGDPR: true,
    synonyms: [],
    alpha2: 'fi',
    countryCode: 246,
    nationality: 'Finnish',
    translations: {he: 'פינלנד', fr: 'Finlande', es: 'Finlandia'},
    pluralNation: {
      en: 'Finns',
      he: 'פינים',
      fr: 'Finlandais',
      es: 'finladeses',
    },
  },
  {
    name: 'France',
    isGDPR: true,
    synonyms: [],
    alpha2: 'fr',
    countryCode: 250,
    nationality: 'French',
    translations: {he: 'צרפת', fr: '', es: 'Francia'},
    pluralNation: {en: 'French', he: 'צרפתים', fr: 'Français', es: 'franceses'},
  },
  {
    name: 'French Guiana',
    synonyms: [],
    alpha2: 'gf',
    countryCode: 254,
    nationality: 'French Guianese',
    translations: {he: 'גינאה הצרפתית', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'French Polynesia',
    synonyms: [],
    alpha2: 'pf',
    countryCode: 258,
    nationality: 'French Polynesian',
    translations: {he: 'פולינזיה הצרפתית', fr: '', es: ''},
    pluralNation: {es: 'Francopolinesios'},
  },
  {
    name: 'French Southern Territories',
    synonyms: [],
    alpha2: 'tf',
    countryCode: 260,
    nationality: 'French Southern Territories',
    translations: {he: 'הארצות הדרומיות והאנטרקטיות של צרפת', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Gabon',
    synonyms: [],
    alpha2: 'ga',
    countryCode: 266,
    nationality: 'Gabonese',
    translations: {he: 'גבון', fr: '', es: 'Gabón'},
    pluralNation: {en: 'Gabonese', fr: 'Gabonais', es: 'Gabonéses'},
  },
  {
    name: 'Gambia',
    synonyms: [],
    alpha2: 'gm',
    countryCode: 270,
    nationality: 'Gambian',
    translations: {he: 'גמביה', fr: 'Gambie', es: ''},
    pluralNation: {
      en: 'Gambians',
      he: 'גמבים',
      fr: 'Gambiens',
      es: 'Gambianos',
    },
  },
  {
    name: 'Georgia',
    synonyms: [],
    alpha2: 'ge',
    countryCode: 268,
    nationality: 'Georgian',
    translations: {he: 'גאורגיה', fr: 'Géorgie', es: ''},
    pluralNation: {
      en: 'Georgians',
      he: 'גיאורגים',
      fr: 'Géorgiens',
      es: 'Georgianos',
    },
  },
  {
    name: 'Germany',
    isGDPR: true,
    synonyms: [],
    alpha2: 'de',
    countryCode: 276,
    nationality: 'German',
    translations: {he: 'גרמניה', fr: 'Allemagne', es: 'Alemania'},
    pluralNation: {
      en: 'Germans',
      he: 'גרמנים',
      fr: 'Allemands',
      es: 'alemanes',
    },
  },
  {
    name: 'Ghana',
    synonyms: [],
    alpha2: 'gh',
    countryCode: 288,
    nationality: 'Ghanaian',
    translations: {he: 'גאנה', fr: '', es: ''},
    pluralNation: {
      en: 'Ghanaians',
      he: 'גנאים',
      fr: 'Ghanéens',
      es: 'Ghanéses',
    },
  },
  {
    name: 'Gibraltar',
    synonyms: [],
    alpha2: 'gi',
    countryCode: 292,
    nationality: 'Gibraltar',
    translations: {he: 'גיברלטר', fr: '', es: ''},
    pluralNation: {he: 'גיברלטרים', es: 'gibraltareños'},
  },
  {
    name: 'Greece',
    isGDPR: true,
    synonyms: [],
    alpha2: 'gr',
    countryCode: 300,
    nationality: 'Greek, Hellenic',
    translations: {he: 'יוון', fr: 'Grèce', es: 'Grecia'},
    pluralNation: {en: 'Greeks', he: 'יוונים', fr: 'Grecs', es: 'griegos'},
  },
  {
    name: 'Greenland',
    synonyms: [],
    alpha2: 'gl',
    countryCode: 304,
    nationality: 'Greenlandic',
    translations: {he: 'גרינלנד', fr: '', es: ''},
    pluralNation: {en: 'Greenlanders', he: 'גרינלנדים', es: 'groenlandéses'},
  },
  {
    name: 'Grenada',
    synonyms: [],
    alpha2: 'gd',
    countryCode: 308,
    nationality: 'Grenadian',
    translations: {he: 'גרנאדה', fr: 'Grenade', es: ''},
    pluralNation: {en: 'Grenadians', fr: 'Grenadiens', es: 'granadinos'},
  },
  {
    name: 'Guadeloupe',
    synonyms: [],
    alpha2: 'gp',
    countryCode: 312,
    nationality: 'Guadeloupe',
    translations: {he: 'גוואדלפור', fr: '', es: ''},
    pluralNation: {he: 'גוואדלופים', es: 'Guadalupeños'},
  },
  {
    name: 'Guam',
    synonyms: [],
    alpha2: 'gu',
    countryCode: 316,
    nationality: 'Guamanian, Guambat',
    translations: {he: 'גואם', fr: '', es: ''},
    pluralNation: {es: 'guameños'},
  },
  {
    name: 'Guatemala',
    synonyms: ['Rep. de Guatemala', 'República de Guatemala', 'Gua'],
    alpha2: 'gt',
    countryCode: 320,
    nationality: 'Guatemalan',
    translations: {he: 'גוואטמאלה', fr: '', es: ''},
    pluralNation: {
      en: 'Guatemalans',
      he: 'גוואטמאלים',
      fr: 'Guatémaltèques',
      es: 'guatemaltecos',
    },
  },
  {
    name: 'Guernsey',
    synonyms: [],
    alpha2: 'gg',
    countryCode: 831,
    nationality: 'Channel Island',
    translations: {he: 'גרנזי', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Guinea',
    synonyms: [],
    alpha2: 'gn',
    countryCode: 324,
    nationality: 'Guinean',
    translations: {he: 'גינאה', fr: 'Guinée', es: ''},
    pluralNation: {en: 'Guineans', fr: 'Guinéens', es: 'Guineanos'},
  },
  {
    name: 'Guinea-Bissau',
    synonyms: [],
    alpha2: 'gw',
    countryCode: 624,
    nationality: 'Bissau-Guinean',
    translations: {he: 'גינאה ביסאו', fr: 'Guinée-Bissau', es: ''},
    pluralNation: {fr: 'Bissau-Guinéens', es: 'bisauguineanos'},
  },
  {
    name: 'Guyana',
    synonyms: [],
    alpha2: 'gy',
    countryCode: 328,
    nationality: 'Guyanese',
    translations: {he: 'גיאנה', fr: '', es: ''},
    pluralNation: {
      en: 'Guyanese',
      he: 'גיאנים',
      fr: 'Guyaniens',
      es: 'guyanéses',
    },
  },
  {
    name: 'Haiti',
    synonyms: [],
    alpha2: 'ht',
    countryCode: 332,
    nationality: 'Haitian',
    translations: {he: 'האיטי', fr: 'Haïti', es: 'Haití'},
    pluralNation: {
      en: 'Haitians',
      he: 'האיטים',
      fr: 'Haïtiens',
      es: 'haitianos',
    },
  },
  {
    name: 'Honduras',
    synonyms: ['República de Honduras', 'Rep. de Honduras', 'Hon'],
    alpha2: 'hn',
    countryCode: 340,
    nationality: 'Honduran',
    translations: {he: 'הונדורס', fr: '', es: ''},
    pluralNation: {
      en: 'Hondurans',
      he: 'הונדורים',
      fr: 'Honduriens',
      es: 'hondureños',
    },
  },
  {
    name: 'Hong Kong',
    synonyms: [],
    alpha2: 'hk',
    countryCode: 344,
    nationality: 'Hong Kong, Hong Kongese',
    translations: {he: 'הונג קונג', fr: '', es: ''},
    pluralNation: {he: 'הונג קונגים', es: 'hongkonéses'},
  },
  {
    name: 'Hungary',
    isGDPR: true,
    synonyms: [],
    alpha2: 'hu',
    countryCode: 348,
    nationality: 'Hungarian, Magyar',
    translations: {he: 'הונגריה', fr: 'Hongrie', es: 'Hungría'},
    pluralNation: {
      en: 'Hungarians',
      he: 'הונגרים',
      fr: 'Hongrois',
      es: 'hungarós',
    },
  },
  {
    name: 'Iceland',
    synonyms: [],
    alpha2: 'is',
    countryCode: 352,
    nationality: 'Icelandic',
    translations: {he: 'איסלנד', fr: 'Islande', es: 'Islandia'},
    pluralNation: {
      en: 'Icelanders',
      he: 'איסלנדים',
      fr: 'Islandais',
      es: 'Islandéses',
    },
  },
  {
    name: 'India',
    synonyms: [],
    alpha2: 'in',
    countryCode: 356,
    nationality: 'Indian',
    translations: {he: 'הודו', fr: 'Inde', es: ''},
    pluralNation: {en: 'Indians', he: 'הודים', fr: 'Indiens', es: 'indios'},
  },
  {
    name: 'Indonesia',
    synonyms: [],
    alpha2: 'id',
    countryCode: 360,
    nationality: 'Indonesian',
    translations: {he: 'אינדונזיה', fr: 'Indonésie', es: ''},
    pluralNation: {
      en: 'Indonesians',
      he: 'אינדונזים',
      fr: 'Indonésiens',
      es: 'Indonesios',
    },
  },
  {
    name: 'Iran',
    synonyms: [],
    alpha2: 'ir',
    countryCode: 364,
    nationality: 'Iranian, Persian',
    translations: {
      he: 'אירן',
      fr: "Iran (République islamique dֿ')",
      es: 'Irán (República Islámica del)',
    },
    pluralNation: {en: 'Iranians', he: 'איראנים', fr: 'Iraniens', es: 'iranís'},
  },
  {
    name: 'Iraq',
    synonyms: [],
    alpha2: 'iq',
    countryCode: 368,
    nationality: 'Iraqi',
    translations: {he: 'עירק', fr: '', es: ''},
    pluralNation: {en: 'Iraqis', he: 'עירקים', fr: 'Irakiens', es: 'Iraquís'},
  },
  {
    name: 'Ireland',
    isGDPR: true,
    synonyms: [],
    alpha2: 'ie',
    countryCode: 372,
    nationality: 'Irish',
    translations: {he: 'אירלנד', fr: 'Irlande', es: 'Irlanda'},
    pluralNation: {en: 'Irish', he: 'אירים', fr: 'Irlandais', es: 'irlandeses'},
  },
  {
    name: 'Isle of Man',
    synonyms: [],
    alpha2: 'im',
    countryCode: 833,
    nationality: 'Manx',
    translations: {he: 'האי מאן', fr: '', es: ''},
    pluralNation: {es: 'manéses'},
  },
  {
    name: 'Israel',
    synonyms: [],
    alpha2: 'il',
    countryCode: 376,
    nationality: 'Israeli',
    translations: {he: 'ישראל', fr: 'Israël', es: ''},
    pluralNation: {
      en: 'Israelis',
      he: 'ישראלים',
      fr: 'Israéliens',
      es: 'israelís',
    },
  },
  {
    name: 'Italy',
    isGDPR: true,
    synonyms: [],
    alpha2: 'it',
    countryCode: 380,
    nationality: 'Italian',
    translations: {he: 'איטליה', fr: 'Italie', es: 'Italia'},
    pluralNation: {
      en: 'Italians',
      he: 'איטלקים',
      fr: 'Italiens',
      es: 'italianos',
    },
  },
  {
    name: 'Jamaica',
    synonyms: [],
    alpha2: 'jm',
    countryCode: 388,
    nationality: 'Jamaican',
    translations: {he: 'ג׳מייקה', fr: 'Jamaïque', es: ''},
    pluralNation: {
      en: 'Jamaicans',
      he: 'ג׳מייקנים',
      fr: 'Jamaïcains',
      es: 'amaiquinos',
    },
  },
  {
    name: 'Japan',
    synonyms: [],
    alpha2: 'jp',
    countryCode: 392,
    nationality: 'Japanese',
    translations: {he: 'יפן', fr: 'Japon', es: 'Japón'},
    pluralNation: {
      en: 'Japanese',
      he: 'יפנים',
      fr: 'Japonais',
      es: 'japoneses',
    },
  },
  {
    name: 'Jordan',
    synonyms: [],
    alpha2: 'jo',
    countryCode: 400,
    nationality: 'Jordanian',
    translations: {he: 'ירדן', fr: 'Jordanie', es: 'Jordania'},
    pluralNation: {
      en: 'Jordanians',
      he: 'ירדנים',
      fr: 'Jordaniens',
      es: 'Jordanos',
    },
  },
  {
    name: 'Kazakhstan',
    synonyms: [],
    alpha2: 'kz',
    countryCode: 398,
    nationality: 'Kazakhstani, Kazakh',
    translations: {he: 'קזחסטן', fr: '', es: 'Kazajstán'},
    pluralNation: {
      en: 'Kazakhs',
      he: 'קזחים',
      fr: 'Kazakhs',
      es: 'Kazajos o kazakos',
    },
  },
  {
    name: 'Kenya',
    synonyms: [],
    alpha2: 'ke',
    countryCode: 404,
    nationality: 'Kenyan',
    translations: {he: 'קנייה', fr: '', es: ''},
    pluralNation: {en: 'Kenyans', he: 'קנייתים', fr: 'Kenyans', es: 'kenianos'},
  },
  {
    name: 'Kiribati',
    synonyms: [],
    alpha2: 'ki',
    countryCode: 296,
    nationality: 'I-Kiribati',
    translations: {he: 'קיריבטי', fr: '', es: ''},
    pluralNation: {fr: 'Kiribatiens', es: 'Kiribatianos'},
  },
  {
    name: 'North Korea',
    synonyms: [],
    alpha2: 'kp',
    countryCode: 408,
    nationality: 'North Korean',
    translations: {he: 'קוריאה הצפונית', fr: '', es: ''},
    pluralNation: {en: 'North Koreans', he: 'צפון קוריאנים', es: 'norcoreanos'},
  },
  {
    name: 'South Korea',
    synonyms: [],
    alpha2: 'kr',
    countryCode: 410,
    nationality: 'South Korean',
    translations: {he: 'קוריאה הדרומית', fr: '', es: ''},
    pluralNation: {en: 'South Koreans', he: 'דרום קוריאנים', es: 'surcoreanos'},
  },
  {
    name: 'Kuwait',
    synonyms: [],
    alpha2: 'kw',
    countryCode: 414,
    nationality: 'Kuwaiti',
    translations: {he: 'כווית', fr: 'Koweït', es: ''},
    pluralNation: {
      en: 'Kuwaitis',
      he: 'כוויתים',
      fr: 'Koweïtiens',
      es: 'Kuwaitis',
    },
  },
  {
    name: 'Kyrgyzstan',
    synonyms: ['Kirghizie', 'Kirghizistan'],
    alpha2: 'kg',
    countryCode: 417,
    nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz',
    translations: {he: 'קירגיסטן', fr: 'Kirghizistan', es: 'Kirguistán'},
    pluralNation: {
      en: 'Kyrgyz',
      he: 'קירגיזים',
      fr: 'Kirghizes',
      es: 'Kirguís',
    },
  },
  {
    name: 'Lao',
    synonyms: [],
    alpha2: 'la',
    countryCode: 418,
    nationality: 'Lao, Laotian',
    translations: {
      he: 'לאוס',
      fr: 'République démocratique populaire lao',
      es: 'República Democrática Popular Lao',
    },
    pluralNation: {fr: 'Laotiens', es: 'laosianos'},
  },
  {
    name: 'Latvia',
    isGDPR: true,
    synonyms: [],
    alpha2: 'lv',
    countryCode: 428,
    nationality: 'Latvian',
    translations: {he: 'לטביה', fr: 'Lettonie', es: 'Letonia'},
    pluralNation: {
      en: 'Latvians',
      he: 'לטבים',
      fr: 'Lettons',
      es: 'letónianos',
    },
  },
  {
    name: 'Lebanon',
    synonyms: [],
    alpha2: 'lb',
    countryCode: 422,
    nationality: 'Lebanese',
    translations: {he: 'לבנון', fr: 'Liban', es: 'Líbano'},
    pluralNation: {
      en: 'Lebanese',
      he: 'לבנונים',
      fr: 'Libanais',
      es: 'Libanéses',
    },
  },
  {
    name: 'Lesotho',
    synonyms: [],
    alpha2: 'ls',
    countryCode: 426,
    nationality: 'Basotho',
    translations: {he: 'לסוטו', fr: '', es: ''},
    pluralNation: {fr: 'Lesothans', es: 'Lesotenses'},
  },
  {
    name: 'Liberia',
    synonyms: [],
    alpha2: 'lr',
    countryCode: 430,
    nationality: 'Liberian',
    translations: {he: 'ליבריה', fr: 'Libéria', es: ''},
    pluralNation: {
      en: 'Liberians',
      he: 'ליברים',
      fr: 'Libériens',
      es: 'Liberianos',
    },
  },
  {
    name: 'Libya',
    synonyms: [],
    alpha2: 'ly',
    countryCode: 434,
    nationality: 'Libyan',
    translations: {he: 'לוב', fr: 'Libye', es: 'Libia'},
    pluralNation: {en: 'Libyans', he: 'לובים', fr: 'Libyens', es: 'libios'},
  },
  {
    name: 'Liechtenstein',
    synonyms: [],
    alpha2: 'li',
    countryCode: 438,
    nationality: 'Liechtenstein',
    translations: {he: 'ליכטנשטיין', fr: '', es: ''},
    pluralNation: {
      en: 'Liechtensteiners',
      he: 'ליכטנשטיינים',
      fr: 'Liechtensteinois',
      es: 'liechtensteinianos',
    },
  },
  {
    name: 'Lithuania',
    isGDPR: true,
    synonyms: [],
    alpha2: 'lt',
    countryCode: 440,
    nationality: 'Lithuanian',
    translations: {he: 'ליטא', fr: 'Lituanie', es: 'Lituania'},
    pluralNation: {
      en: 'Lithuanians',
      he: 'ליטאים',
      fr: 'Lituaniens',
      es: 'lituanos',
    },
  },
  {
    name: 'Luxembourg',
    isGDPR: true,
    synonyms: [],
    alpha2: 'lu',
    countryCode: 442,
    nationality: 'Luxembourg, Luxembourgish',
    translations: {he: 'לוקסמבורג', fr: '', es: 'Luxemburgo'},
    pluralNation: {
      en: 'Luxembourgers',
      he: 'לוקסמבורגים',
      fr: 'Luxembourgeois',
      es: 'Luxemburguéses',
    },
  },
  {
    name: 'Macao',
    synonyms: [],
    alpha2: 'mo',
    countryCode: 446,
    nationality: 'Macanese, Chinese',
    translations: {he: 'מקאו', fr: '', es: ''},
    pluralNation: {en: 'Macaos', es: 'Macaenses'},
  },
  {
    name: 'Macedonia',
    synonyms: [],
    alpha2: 'mk',
    countryCode: 807,
    nationality: 'Macedonian',
    translations: {he: 'מקדוניה', fr: '', es: ''},
    pluralNation: {
      en: 'Macedonians',
      he: 'מקדונים',
      es: 'macedonios\nnormacedonios',
    },
  },
  {
    name: 'Madagascar',
    synonyms: [],
    alpha2: 'mg',
    countryCode: 450,
    nationality: 'Malagasy',
    translations: {he: 'מדגסקר', fr: '', es: ''},
    pluralNation: {
      en: 'Madagascans',
      he: 'מדגסקרים',
      fr: 'Malgaches',
      es: 'Malgaches',
    },
  },
  {
    name: 'Malawi',
    synonyms: [],
    alpha2: 'mw',
    countryCode: 454,
    nationality: 'Malawian',
    translations: {he: 'מלאווי', fr: '', es: ''},
    pluralNation: {en: 'Malawians', fr: 'Malawites', es: 'Malauís'},
  },
  {
    name: 'Malaysia',
    synonyms: [],
    alpha2: 'my',
    countryCode: 458,
    nationality: 'Malaysian',
    translations: {he: 'מלזיה', fr: 'Malaisie', es: 'Malasia'},
    pluralNation: {
      en: 'Malaysians',
      he: 'מלזים',
      fr: 'Malaisiens',
      es: 'Malasios',
    },
  },
  {
    name: 'Maldives',
    synonyms: [],
    alpha2: 'mv',
    countryCode: 462,
    nationality: 'Maldivian',
    translations: {he: 'מלדיבים', fr: 'Maldives', es: 'Maldivas'},
    pluralNation: {en: 'Maldivians', fr: 'Maldiviens', es: 'maldivios'},
  },
  {
    name: 'Mali',
    synonyms: [],
    alpha2: 'ml',
    countryCode: 466,
    nationality: 'Malian, Malinese',
    translations: {he: 'מאלי', fr: '', es: ''},
    pluralNation: {en: 'Malians', fr: 'Maliens', es: 'malienses'},
  },
  {
    name: 'Malta',
    isGDPR: true,
    synonyms: [],
    alpha2: 'mt',
    countryCode: 470,
    nationality: 'Maltese',
    translations: {he: 'מלטה', fr: 'Malte', es: ''},
    pluralNation: {en: 'Maltese', he: 'מלטזים', fr: 'Maltais', es: 'maltéses'},
  },
  {
    name: 'Marshall Islands',
    synonyms: [],
    alpha2: 'mh',
    countryCode: 584,
    nationality: 'Marshallese',
    translations: {he: 'איי מרשל', fr: 'Îles Marshall', es: 'Islas Marshall'},
    pluralNation: {fr: 'Marshallais', es: 'marshaléses'},
  },
  {
    name: 'Martinique',
    synonyms: [],
    alpha2: 'mq',
    countryCode: 474,
    nationality: 'Martiniquais, Martinican',
    translations: {he: 'מרטיניק', fr: '', es: ''},
    pluralNation: {en: 'Martinique', es: 'martiniqueños,'},
  },
  {
    name: 'Mauritania',
    synonyms: [],
    alpha2: 'mr',
    countryCode: 478,
    nationality: 'Mauritanian',
    translations: {he: 'מאוריטניה', fr: 'Mauritanie', es: ''},
    pluralNation: {en: 'Mauritanians', fr: 'Mauritaniens', es: 'mauritanos'},
  },
  {
    name: 'Mauritius',
    synonyms: [],
    alpha2: 'mu',
    countryCode: 480,
    nationality: 'Mauritian',
    translations: {he: 'מאוריציוס', fr: 'Maurice', es: 'Mauricio'},
    pluralNation: {
      en: 'Mauritians',
      he: 'מאוריציוסים',
      fr: 'Mauriciens',
      es: 'mauricianos',
    },
  },
  {
    name: 'Mayotte',
    synonyms: [],
    alpha2: 'yt',
    countryCode: 175,
    nationality: 'Mahoran',
    translations: {he: 'מאמודזו', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Mexico',
    synonyms: ['MX', 'Estados Unidos Mexicanos'],
    alpha2: 'mx',
    countryCode: 484,
    nationality: 'Mexican',
    translations: {he: 'מקסיקו', fr: 'Mexique', es: 'México'},
    pluralNation: {
      en: 'Mexicans',
      he: 'מקסיקנים',
      fr: 'Mexicains',
      es: 'mexicanos',
    },
  },
  {
    name: 'Micronesia',
    synonyms: [],
    alpha2: 'fm',
    countryCode: 583,
    nationality: 'Micronesian',
    translations: {
      he: 'מיקרונזיה',
      fr: 'Micronésie (États fédérés de)',
      es: 'Micronesia (Estados Federados de)',
    },
    pluralNation: {
      en: 'Micronesians',
      he: 'מיקרונזים',
      fr: 'Micronésiens',
      es: 'micronesios',
    },
  },
  {
    name: 'Moldova',
    synonyms: [],
    alpha2: 'md',
    countryCode: 498,
    nationality: 'Moldovan',
    translations: {he: 'מודלובה', fr: '', es: ''},
    pluralNation: {en: 'Moldovans', he: 'מולדובים'},
  },
  {
    name: 'Monaco',
    synonyms: [],
    alpha2: 'mc',
    countryCode: 492,
    nationality: 'Monégasque, Monacan',
    translations: {he: 'מונקו', fr: '', es: 'Mónaco'},
    pluralNation: {
      en: 'Monacoians',
      he: 'תושבי מונקו',
      fr: 'Monégasques',
      es: 'Monegascos',
    },
  },
  {
    name: 'Mongolia',
    synonyms: [],
    alpha2: 'mn',
    countryCode: 496,
    nationality: 'Mongolian',
    translations: {he: 'מונגוליה', fr: 'Mongolie', es: ''},
    pluralNation: {
      en: 'Mongolians',
      he: 'מונגולים',
      fr: 'Mongols',
      es: 'Mongoles',
    },
  },
  {
    name: 'Montenegro',
    synonyms: [],
    alpha2: 'me',
    countryCode: 499,
    nationality: 'Montenegrin',
    translations: {he: 'מונטנגרו', fr: 'Monténégro', es: ''},
    pluralNation: {
      en: 'Montenegrins',
      he: 'מונטנגרואים',
      fr: 'Monténégrins',
      es: 'Montenegrinos',
    },
  },
  {
    name: 'Montserrat',
    synonyms: [],
    alpha2: 'ms',
    countryCode: 500,
    nationality: 'Montserratian',
    translations: {he: 'מונטסראט', fr: '', es: ''},
    pluralNation: {en: 'Montserratians', es: 'montserratenses'},
  },
  {
    name: 'Morocco',
    synonyms: [],
    alpha2: 'ma',
    countryCode: 504,
    nationality: 'Moroccan',
    translations: {he: 'מרוקו', fr: 'Maroc', es: 'Marruecos'},
    pluralNation: {
      en: 'Moroccans',
      he: 'מרוקאים',
      fr: 'Marocains',
      es: 'marroquis',
    },
  },
  {
    name: 'Mozambique',
    synonyms: [],
    alpha2: 'mz',
    countryCode: 508,
    nationality: 'Mozambican',
    translations: {he: 'מוזמביק', fr: '', es: ''},
    pluralNation: {en: 'Mozambicans', fr: 'Mozambicains', es: 'mozambiqueños'},
  },
  {
    name: 'Myanmar',
    synonyms: ['Birmanie'],
    alpha2: 'mm',
    countryCode: 104,
    nationality: 'Burmese',
    translations: {he: 'מיאנמר', fr: '', es: ''},
    pluralNation: {
      en: 'Myanmars',
      he: 'מיאנמרים',
      fr: 'Myanmarais',
      es: 'birmanos',
    },
  },
  {
    name: 'Namibia',
    synonyms: [],
    alpha2: 'na',
    countryCode: 516,
    nationality: 'Namibian',
    translations: {he: 'נמיביה', fr: 'Namibie', es: ''},
    pluralNation: {
      en: 'Namibians',
      he: 'נמיבים',
      fr: 'Namibiens',
      es: 'namibios',
    },
  },
  {
    name: 'Nauru',
    synonyms: [],
    alpha2: 'nr',
    countryCode: 520,
    nationality: 'Nauruan',
    translations: {he: 'נאורו', fr: '', es: ''},
    pluralNation: {en: 'Nauruans', fr: 'Nauruans', es: 'Nauruanos'},
  },
  {
    name: 'Nepal',
    synonyms: [],
    alpha2: 'np',
    countryCode: 524,
    nationality: 'Nepali, Nepalese',
    translations: {he: 'נפאל', fr: 'Népal', es: ''},
    pluralNation: {en: 'Nepalese', he: 'נפאלים', fr: 'Népalais', es: 'nepalís'},
  },
  {
    name: 'Netherlands',
    isGDPR: true,
    synonyms: ['Netherland', 'Holland', 'Holand', 'Hollande'],
    alpha2: 'nl',
    countryCode: 528,
    nationality: 'Dutch, Netherlandic',
    translations: {he: 'הולנד', fr: 'Pays-Bas', es: 'Países Bajos'},
    pluralNation: {
      en: 'Dutch',
      he: 'הולנדים',
      fr: 'Néerlandais',
      es: 'Neerlandéses',
    },
  },
  {
    name: 'New Caledonia',
    synonyms: [],
    alpha2: 'nc',
    countryCode: 540,
    nationality: 'New Caledonian',
    translations: {he: 'קלדוניה החדשה', fr: '', es: ''},
    pluralNation: {es: 'Neocaledonios'},
  },
  {
    name: 'New Zealand',
    synonyms: [],
    alpha2: 'nz',
    countryCode: 554,
    nationality: 'New Zealand, NZ',
    translations: {
      he: 'ניו זילנד',
      fr: 'Nouvelle-Zélande',
      es: 'Nueva Zelandia',
    },
    pluralNation: {
      en: 'New Zealanders',
      he: 'ניו זילנדים',
      fr: 'Néo-Zélandais',
      es: 'Neozelandéses',
    },
  },
  {
    name: 'Nicaragua',
    synonyms: ['República de Nicaragua', 'Rep. de Nicaragua', 'Nic'],
    alpha2: 'ni',
    countryCode: 558,
    nationality: 'Nicaraguan',
    translations: {he: 'ניקרגואה', fr: '', es: ''},
    pluralNation: {
      en: 'Nicaraguans',
      he: 'ניקרגואים',
      fr: 'Nicaraguayens',
      es: 'nicaragüenses',
    },
  },
  {
    name: 'Niger',
    synonyms: [],
    alpha2: 'ne',
    countryCode: 562,
    nationality: 'Nigerien',
    translations: {he: 'ניגר', fr: '', es: ''},
    pluralNation: {
      en: 'Nigeriens',
      he: 'ניז׳רים',
      fr: 'Nigériens',
      es: 'Nigerinos.',
    },
  },
  {
    name: 'Nigeria',
    synonyms: [],
    alpha2: 'ng',
    countryCode: 566,
    nationality: 'Nigerian',
    translations: {he: 'ניגריה', fr: 'Nigéria', es: ''},
    pluralNation: {
      en: 'Nigerians',
      he: 'ניגרים',
      fr: 'Nigérians',
      es: 'nigerianos',
    },
  },
  {
    name: 'Niue',
    synonyms: [],
    alpha2: 'nu',
    countryCode: 570,
    nationality: 'Niuean',
    translations: {he: 'ניואה', fr: '', es: ''},
    pluralNation: {en: 'Niue', es: 'niueños'},
  },
  {
    name: 'Norfolk Island',
    synonyms: [],
    alpha2: 'nf',
    countryCode: 574,
    nationality: 'Norfolk Island',
    translations: {he: 'האי נורפולק', fr: '', es: ''},
    pluralNation: {en: 'Norfolk Islanders', es: 'Norfolkenses'},
  },
  {
    name: 'Northern Mariana Islands',
    synonyms: [],
    alpha2: 'mp',
    countryCode: 580,
    nationality: 'Northern Marianan',
    translations: {he: 'איי מריאנה הצפוניים', fr: '', es: ''},
    pluralNation: {es: 'normarianos'},
  },
  {
    name: 'Norway',
    synonyms: [],
    alpha2: 'no',
    countryCode: 578,
    nationality: 'Norwegian',
    translations: {he: 'נורווגיה', fr: 'Norvège', es: 'Noruega'},
    pluralNation: {
      en: 'Norwegians',
      he: 'נורווגים',
      fr: 'Norvégiens',
      es: 'noruegos',
    },
  },
  {
    name: 'Oman',
    synonyms: [],
    alpha2: 'om',
    countryCode: 512,
    nationality: 'Omani',
    translations: {he: 'אומן', fr: '', es: 'Omán'},
    pluralNation: {en: 'Omanis', fr: 'Omanis', es: 'Omanís'},
  },
  {
    name: 'Pakistan',
    synonyms: [],
    alpha2: 'pk',
    countryCode: 586,
    nationality: 'Pakistani',
    translations: {he: 'פקיסטן', fr: '', es: 'Pakistán'},
    pluralNation: {
      en: 'Pakistanis',
      he: 'פקיסטנים',
      fr: 'Pakistanais',
      es: 'pakistanís',
    },
  },
  {
    name: 'Palau',
    synonyms: ['Palau'],
    alpha2: 'pw',
    countryCode: 585,
    nationality: 'Palauan',
    translations: {he: 'פלאו', fr: 'Palaos', es: ''},
    pluralNation: {en: 'Palaus', fr: 'Palauans', es: 'Palauanos'},
  },
  {
    name: 'Palestine',
    synonyms: [],
    alpha2: 'ps',
    countryCode: 275,
    nationality: 'Palestinian',
    translations: {he: 'פלסטין', fr: '', es: ''},
    pluralNation: {en: 'Palestinians', he: 'פלסטינאים', es: 'palestinos'},
  },
  {
    name: 'Panama',
    synonyms: ['Pan', 'Rep', 'de Panamá', 'República de Panamá'],
    alpha2: 'pa',
    countryCode: 591,
    nationality: 'Panamanian',
    translations: {he: 'פנמה', fr: '', es: 'Panamá'},
    pluralNation: {
      en: 'Panamanians',
      he: 'פנמים',
      fr: 'Panaméens',
      es: 'panameños',
    },
  },
  {
    name: 'Papua New Guinea',
    synonyms: [],
    alpha2: 'pg',
    countryCode: 598,
    nationality: 'Papua New Guinean, Papuan',
    translations: {
      he: 'פפואה גינאה',
      fr: 'Papouasie-Nouvelle-Guinée',
      es: 'Papua Nueva Guinea',
    },
    pluralNation: {en: 'Papua New Guineans', fr: 'Papouasiens', es: 'papús,'},
  },
  {
    name: 'Paraguay',
    synonyms: ['Rep. de Paraguay', 'República de Paraguay', 'Par'],
    alpha2: 'py',
    countryCode: 600,
    nationality: 'Paraguayan',
    translations: {he: 'פרגוואי', fr: '', es: ''},
    pluralNation: {
      en: 'Paraguayans',
      he: 'פרגוואים',
      fr: 'Paraguayens',
      es: 'paraguayos',
    },
  },
  {
    name: 'Peru',
    synonyms: ['República de Perú', 'Rep de Perú', 'Per'],
    alpha2: 'pe',
    countryCode: 604,
    nationality: 'Peruvian',
    translations: {he: 'פרו', fr: 'Pérou', es: 'Perú'},
    pluralNation: {
      en: 'Peruvians',
      he: 'פרואנים',
      fr: 'Péruviens',
      es: 'peruanos',
    },
  },
  {
    name: 'Philippines',
    synonyms: ['Philippines Philippine'],
    alpha2: 'ph',
    countryCode: 608,
    nationality: 'Philippine, Filipino',
    translations: {he: 'פיליפינים', fr: 'Philippines', es: 'Filipinas'},
    pluralNation: {
      en: 'Filipinos',
      he: 'פיליפינים',
      fr: 'Philippins',
      es: 'filipinos',
    },
  },
  {
    name: 'Pitcairn',
    synonyms: [],
    alpha2: 'pn',
    countryCode: 612,
    nationality: 'Pitcairn Island',
    translations: {he: 'איי פיטקיירן', fr: '', es: ''},
    pluralNation: {en: 'Pitcairn Islanders', es: 'Pitcairnéses'},
  },
  {
    name: 'Poland',
    isGDPR: true,
    synonyms: ['Pole'],
    alpha2: 'pl',
    countryCode: 616,
    nationality: 'Polish',
    translations: {he: 'פולין', fr: 'Pologne', es: 'Polonia'},
    pluralNation: {en: 'Polish', he: 'פולנים', fr: 'Polonais', es: 'polacos'},
  },
  {
    name: 'Portugal',
    isGDPR: true,
    synonyms: ['Portuguese'],
    alpha2: 'pt',
    countryCode: 620,
    nationality: 'Portuguese',
    translations: {he: 'פורטוגל', fr: '', es: ''},
    pluralNation: {
      en: 'Portuguese',
      he: 'פורטוגזים',
      fr: 'Portugais',
      es: 'portugueses',
    },
  },
  {
    name: 'Puerto Rico',
    synonyms: [
      'פורטו ריקו',
      'פורטוריקו',
      'פוארטו ריקו',
      'פוארטוריקו',
      'PR',
      'La isla',
      'Estado Libre Asociado de Puerto Rico',
    ],
    alpha2: 'pr',
    countryCode: 630,
    nationality: 'Puerto Rican',
    translations: {he: 'פורטו ריקו', fr: '', es: ''},
    pluralNation: {en: 'Puerto Ricans', he: 'פורטו ריקנים', es: 'boricuas'},
  },
  {
    name: 'Qatar',
    synonyms: [],
    alpha2: 'qa',
    countryCode: 634,
    nationality: 'Qatari',
    translations: {he: 'קטאר', fr: '', es: ''},
    pluralNation: {en: 'Qataris', fr: 'Qataris', es: 'Catarís'},
  },
  {
    name: 'Réunion',
    synonyms: [],
    alpha2: 're',
    countryCode: 638,
    nationality: 'Réunionese, Réunionnais',
    translations: {he: 'ראוניון', fr: '', es: ''},
    pluralNation: {es: 'reunionéses'},
  },
  {
    name: 'Romania',
    isGDPR: true,
    synonyms: [],
    alpha2: 'ro',
    countryCode: 642,
    nationality: 'Romanian',
    translations: {he: 'רומניה', fr: 'Roumanie', es: 'Rumania'},
    pluralNation: {
      en: 'Romanians',
      he: 'רומנים',
      fr: 'Roumains',
      es: 'rumanos',
    },
  },
  {
    name: 'Russian Federation',
    synonyms: ['ברית המועצות'],
    alpha2: 'ru',
    countryCode: 643,
    nationality: 'Russian',
    translations: {
      he: 'רוסיה',
      fr: 'Fédération de Russie',
      es: 'Federación de Rusia',
    },
    pluralNation: {en: 'Russians', he: 'רוסים', fr: 'Russes', es: 'Rusos'},
  },
  {
    name: 'Rwanda',
    synonyms: [],
    alpha2: 'rw',
    countryCode: 646,
    nationality: 'Rwandan',
    translations: {he: 'רואנדה', fr: '', es: ''},
    pluralNation: {
      en: 'Rwandans',
      he: 'רואנדים',
      fr: 'Rwandais',
      es: 'Ruandéses',
    },
  },
  {
    name: 'Saint Barthélemy',
    synonyms: [],
    alpha2: 'bl',
    countryCode: 652,
    nationality: 'Barthélemois',
    translations: {he: 'סן ברתלמי', fr: '', es: ''},
    pluralNation: {en: 'Saint-Barthélemois', es: 'batateros'},
  },
  {
    name: 'Saint Helena',
    synonyms: [],
    alpha2: 'sh',
    countryCode: 654,
    nationality: 'Saint Helenian',
    translations: {he: 'סנט הלנה', fr: '', es: ''},
    pluralNation: {en: 'Saint Helenans'},
  },
  {
    name: 'Saint Kitts and Nevis',
    synonyms: [],
    alpha2: 'kn',
    countryCode: 659,
    nationality: 'Kittitian or Nevisian',
    translations: {
      he: 'סנט קיטס ונוויס',
      fr: 'Saint-Kitts-et-Nevis',
      es: 'Saint Kitts y Nevis',
    },
    pluralNation: {fr: 'Kittitiens et Néviciens', es: 'Sancristobaleños'},
  },
  {
    name: 'Saint Lucia',
    synonyms: [],
    alpha2: 'lc',
    countryCode: 662,
    nationality: 'Saint Lucian',
    translations: {he: 'סנט לוסיה', fr: 'Sainte-Lucie', es: 'Santa Lucía'},
    pluralNation: {en: 'Saint Lucians', fr: 'Saint-Luciens'},
  },
  {
    name: 'Saint Martin (French part)',
    synonyms: [],
    alpha2: 'mf',
    countryCode: 663,
    nationality: 'Saint-Martinoise',
    translations: {he: 'סן מרטן', fr: '', es: ''},
    pluralNation: {en: 'Saint Martins'},
  },
  {
    name: 'Saint Pierre and Miquelon',
    synonyms: [],
    alpha2: 'pm',
    countryCode: 666,
    nationality: 'Saint-Pierrais or Miquelonnais',
    translations: {he: 'סנט פייר ומיקלון', fr: '', es: ''},
    pluralNation: {es: 'Sanpedrinos'},
  },
  {
    name: 'Saint Vincent and the Grenadines',
    synonyms: [],
    alpha2: 'vc',
    countryCode: 670,
    nationality: 'Saint Vincentian, Vincentian',
    translations: {
      he: 'סנט וינסנט והגרנדינים',
      fr: 'Saint-Vincent-et-les Grenadines',
      es: 'San Vicente y las Granadinas',
    },
    pluralNation: {fr: 'Saint-Vincentais et Grenadins', es: 'Sanvicentinos'},
  },
  {
    name: 'Samoa',
    synonyms: [],
    alpha2: 'ws',
    countryCode: 882,
    nationality: 'Samoan',
    translations: {he: 'סמואה', fr: '', es: ''},
    pluralNation: {en: 'Samoans', he: 'סמואים', fr: 'Samoans', es: 'samoanos'},
  },
  {
    name: 'San Marino',
    synonyms: [],
    alpha2: 'sm',
    countryCode: 674,
    nationality: 'Sammarinese',
    translations: {he: 'סן מרינו', fr: 'Saint-Marin', es: ''},
    pluralNation: {fr: 'Saint-Marinais', es: 'Sanmarinenses'},
  },
  {
    name: 'Sao Tome and Principe',
    synonyms: [],
    alpha2: 'st',
    countryCode: 678,
    nationality: 'São Toméan',
    translations: {
      he: 'סאו טומה ופרינסיפה',
      fr: 'Sao Tomé-et-Principe',
      es: 'Santo Tomé y Príncipe',
    },
    pluralNation: {fr: 'Santoméens', es: 'Santotomenses'},
  },
  {
    name: 'Saudi Arabia',
    synonyms: ['Saudi Arabian or Saudi', 'ערב הסעודית'],
    alpha2: 'sa',
    countryCode: 682,
    nationality: 'Saudi, Saudi Arabian',
    translations: {he: 'סעודיה', fr: 'Arabie saoudite', es: 'Arabia Saudita'},
    pluralNation: {en: 'Saudis', he: 'סעודים', fr: 'Saoudiens', es: 'saudís'},
  },
  {
    name: 'Senegal',
    synonyms: [],
    alpha2: 'sn',
    countryCode: 686,
    nationality: 'Senegalese',
    translations: {he: 'סנגל', fr: 'Sénégal', es: ''},
    pluralNation: {
      en: 'Senegalese',
      he: 'סנגלים',
      fr: 'Sénégalais',
      es: 'senegaléses',
    },
  },
  {
    name: 'Serbia',
    synonyms: ['Serb'],
    alpha2: 'rs',
    countryCode: 688,
    nationality: 'Serbian',
    translations: {he: 'סרביה', fr: 'Serbie', es: ''},
    pluralNation: {en: 'Serbians', he: 'סרבים', fr: 'Serbes', es: 'serbios'},
  },
  {
    name: 'Seychelles',
    synonyms: [],
    alpha2: 'sc',
    countryCode: 690,
    nationality: 'Seychellois',
    translations: {he: 'סיישל', fr: 'Seychelles', es: ''},
    pluralNation: {
      en: 'Seychellois',
      he: 'סיישלואה',
      fr: 'Seychellois',
      es: 'Seychellenses',
    },
  },
  {
    name: 'Sierra Leone',
    synonyms: [],
    alpha2: 'sl',
    countryCode: 694,
    nationality: 'Sierra Leonean',
    translations: {he: 'סיירה לאון', fr: '', es: 'Sierra Leona'},
    pluralNation: {
      en: 'Sierra Leoneans',
      fr: 'Sierra-Léonais',
      es: 'sierraloénses',
    },
  },
  {
    name: 'Singapore',
    synonyms: [],
    alpha2: 'sg',
    countryCode: 702,
    nationality: 'Singaporean',
    translations: {he: 'סינגפור', fr: 'Singapour', es: 'Singapur'},
    pluralNation: {
      en: 'Singaporean',
      he: 'סינגפורים',
      fr: 'Singapouriens',
      es: 'Singapurenses',
    },
  },
  {
    name: 'Sint Maarten (Dutch part)',
    synonyms: [],
    alpha2: 'sx',
    countryCode: 534,
    nationality: 'Sint Maarten',
    translations: {he: 'סן מרטין', fr: '', es: ''},
    pluralNation: {es: 'Sanmartinenses'},
  },
  {
    name: 'Slovakia',
    isGDPR: true,
    synonyms: ['Slovak'],
    alpha2: 'sk',
    countryCode: 703,
    nationality: 'Slovak',
    translations: {he: 'סלובקיה', fr: 'Slovaquie', es: 'Eslovaquia'},
    pluralNation: {
      en: 'Slovakians',
      he: 'סלובקים',
      fr: 'Slovaques',
      es: 'Eslovacos',
    },
  },
  {
    name: 'Slovenia',
    isGDPR: true,
    synonyms: ['Slovene'],
    alpha2: 'si',
    countryCode: 705,
    nationality: 'Slovenian, Slovene',
    translations: {he: 'סלובניה', fr: 'Slovénie', es: 'Eslovenia'},
    pluralNation: {
      en: 'Slovenians',
      he: 'סלובנים',
      fr: 'Slovènes',
      es: 'eslovenios',
    },
  },
  {
    name: 'Solomon Islands',
    synonyms: [],
    alpha2: 'sb',
    countryCode: 90,
    nationality: 'Solomon Island',
    translations: {he: 'איי שלמה', fr: 'Îles Salomon', es: 'Islas Salomón'},
    pluralNation: {
      en: 'Solomon Islanders',
      fr: 'Salomonais',
      es: 'Salomonenses',
    },
  },
  {
    name: 'Somalia',
    synonyms: ['Somali'],
    alpha2: 'so',
    countryCode: 706,
    nationality: 'Somali, Somalian',
    translations: {he: 'סומליה', fr: 'Somalie', es: ''},
    pluralNation: {
      en: 'Somalians',
      he: 'סומלים',
      fr: 'Somaliens',
      es: 'Somalís',
    },
  },
  {
    name: 'South Africa',
    synonyms: [],
    alpha2: 'za',
    countryCode: 710,
    nationality: 'South African',
    translations: {he: 'דרום אפריקה', fr: 'Afrique du Sud', es: 'Sudáfrica'},
    pluralNation: {
      en: 'South Africana',
      he: 'דרום אפריקאים',
      fr: 'Sud-Africains',
      es: 'sudafricanos',
    },
  },
  {
    name: 'South Sudan',
    synonyms: [],
    alpha2: 'ss',
    countryCode: 728,
    nationality: 'South Sudanese',
    translations: {he: 'דרום סודן', fr: 'Soudan du Sud', es: 'Sudán del Sur'},
    pluralNation: {
      en: 'Sudanese',
      he: 'דרום סודנים',
      fr: 'Sud-Soudanais',
      es: 'Sursudanéses',
    },
  },
  {
    name: 'Spain',
    isGDPR: true,
    synonyms: ['ES', 'Reino de España'],
    alpha2: 'es',
    countryCode: 724,
    nationality: 'Spanish',
    translations: {he: 'ספרד', fr: 'Espagne', es: 'España'},
    pluralNation: {
      en: 'Spanish',
      he: 'ספרדים',
      fr: 'Espagnols',
      es: 'españoles',
    },
  },
  {
    name: 'Sri Lanka',
    synonyms: [],
    alpha2: 'lk',
    countryCode: 144,
    nationality: 'Sri Lankan',
    translations: {he: 'סרילנקה', fr: '', es: ''},
    pluralNation: {
      en: 'Sri Lankans',
      he: 'סרילנקים',
      fr: 'Srilankais',
      es: 'ceilandéses',
    },
  },
  {
    name: 'Sudan',
    synonyms: ['Sudanese'],
    alpha2: 'sd',
    countryCode: 729,
    nationality: 'Sudanese',
    translations: {he: 'סודן', fr: 'Soudan', es: 'Sudán'},
    pluralNation: {
      en: 'Sudanese',
      he: 'סודנים',
      fr: 'Soudanais',
      es: 'Sudanéses',
    },
  },
  {
    name: 'Suriname',
    synonyms: [],
    alpha2: 'sr',
    countryCode: 740,
    nationality: 'Surinamese',
    translations: {he: 'סורינאם', fr: '', es: ''},
    pluralNation: {en: 'Surinamese', fr: 'Surinamais', es: 'surinaméses'},
  },
  {
    name: 'Svalbard and Jan Mayen',
    synonyms: [],
    alpha2: 'sj',
    countryCode: 744,
    nationality: 'Svalbard',
    translations: {he: 'סבאלברד ויאן מאיין', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Swaziland',
    synonyms: [],
    alpha2: 'sz',
    countryCode: 748,
    nationality: 'Swazi',
    translations: {he: 'סווזילנד', fr: '', es: ''},
    pluralNation: {en: 'Swazis', es: 'Suazis'},
  },
  {
    name: 'Sweden',
    isGDPR: true,
    synonyms: ['Swedish/Swede', 'שוודיה', 'שבדיה'],
    alpha2: 'se',
    countryCode: 752,
    nationality: 'Swedish',
    translations: {he: 'שוודיה', fr: 'Suède', es: 'Suecia'},
    pluralNation: {en: 'Swedish', he: 'שוודים', fr: 'Suédois', es: 'suecos'},
  },
  {
    name: 'Switzerland',
    synonyms: ['Swiss'],
    alpha2: 'ch',
    countryCode: 756,
    nationality: 'Swiss',
    translations: {he: 'שוויץ', fr: 'Suisse', es: 'Suiza'},
    pluralNation: {en: 'Swiss', he: 'שוויצרים', fr: 'Suisses', es: 'Suizos'},
  },
  {
    name: 'Syria',
    synonyms: ['Syrian'],
    alpha2: 'sy',
    countryCode: 760,
    nationality: 'Syrian',
    translations: {he: 'סוריה', fr: 'Syrienne', es: 'Siria'},
    pluralNation: {en: 'Syrians', he: 'סורים', fr: 'Syriens', es: 'sirios'},
  },
  {
    name: 'Taiwan',
    synonyms: [],
    alpha2: 'tw',
    countryCode: 158,
    nationality: 'Chinese, Taiwanese',
    translations: {he: 'טייוואן', fr: '', es: ''},
    pluralNation: {en: 'Taiwanese', he: 'טיוואנים', es: 'Taiwaneses'},
  },
  {
    name: 'Tajikistan',
    synonyms: [],
    alpha2: 'tj',
    countryCode: 762,
    nationality: 'Tajikistani',
    translations: {he: 'טג׳יקיסטן', fr: 'Tadjikistan', es: 'Tayikistán'},
    pluralNation: {en: 'Tadjiks', fr: 'Tadjiks', es: 'tayikos'},
  },
  {
    name: 'Tanzania',
    synonyms: [],
    alpha2: 'tz',
    countryCode: 834,
    nationality: 'Tanzanian',
    translations: {he: 'טנזניה', fr: '', es: ''},
    pluralNation: {en: 'Tanzanians', he: 'טנזנים', es: 'Tanzanos'},
  },
  {
    name: 'Thailand',
    synonyms: ['Thai'],
    alpha2: 'th',
    countryCode: 764,
    nationality: 'Thai',
    translations: {he: 'תאילנד', fr: 'Thaïlande', es: 'Tailandia'},
    pluralNation: {
      en: 'Thais',
      he: 'תאילנדים',
      fr: 'Thaïlandais',
      es: 'tailandeses',
    },
  },
  {
    name: 'Timor-Leste',
    synonyms: [],
    alpha2: 'tl',
    countryCode: 626,
    nationality: 'Timorese',
    translations: {he: 'מזרח טימור', fr: 'Timor-Leste', es: 'Timor-Leste'},
    pluralNation: {en: 'Timorese', fr: 'Est-Timorais', es: 'Timorenses'},
  },
  {
    name: 'Togo',
    synonyms: [],
    alpha2: 'tg',
    countryCode: 768,
    nationality: 'Togolese',
    translations: {he: 'טוגו', fr: '', es: ''},
    pluralNation: {
      en: 'Togolese',
      he: 'תושבי טוגו',
      fr: 'Togolais',
      es: 'Togoléses',
    },
  },
  {
    name: 'Tokelau',
    synonyms: [],
    alpha2: 'tk',
    countryCode: 772,
    nationality: 'Tokelauan',
    translations: {he: 'טוקלאו', fr: '', es: ''},
    pluralNation: {en: 'Tokelauans', es: 'Tokelauanos'},
  },
  {
    name: 'Tonga',
    synonyms: [],
    alpha2: 'to',
    countryCode: 776,
    nationality: 'Tongan',
    translations: {he: 'טונגה', fr: 'Tonga', es: ''},
    pluralNation: {en: 'Tongans', fr: 'Tonguiens', es: 'Tonganos'},
  },
  {
    name: 'Trinidad and Tobago',
    synonyms: [],
    alpha2: 'tt',
    countryCode: 780,
    nationality: 'Trinidadian or Tobagonian',
    translations: {
      he: 'טרינידד טובגו',
      fr: 'Trinité-et-Tobago',
      es: 'Trinidad y Tabago',
    },
    pluralNation: {
      en: 'Trinidadians and Tobagonians',
      he: 'טרינידדים',
      fr: 'Trinidadiens',
      es: 'Trinitenses',
    },
  },
  {
    name: 'Tunisia',
    synonyms: [],
    alpha2: 'tn',
    countryCode: 788,
    nationality: 'Tunisian',
    translations: {he: 'טוניסיה', fr: 'Tunisie', es: 'Túnez'},
    pluralNation: {
      en: 'Tunisians',
      he: 'טוניסאים',
      fr: 'Tunisiens',
      es: 'tunecinos',
    },
  },
  {
    name: 'Turkey',
    synonyms: ['Turkish/turk'],
    alpha2: 'tr',
    countryCode: 792,
    nationality: 'Turkish',
    translations: {he: 'טורקיה', fr: 'Turquie', es: 'Turquía'},
    pluralNation: {en: 'Turkish', he: 'טורקים', fr: 'Turcs', es: 'Turcos'},
  },
  {
    name: 'Turkmenistan',
    synonyms: ['Turkménie'],
    alpha2: 'tm',
    countryCode: 795,
    nationality: 'Turkmen',
    translations: {he: 'טורקמניסטן', fr: 'Turkménistan', es: 'Turkmenistán'},
    pluralNation: {
      en: 'Turkomans',
      he: 'טורקמניסטנים',
      fr: 'Turkmènes',
      es: 'turcomanos',
    },
  },
  {
    name: 'Turks and Caicos Islands',
    synonyms: [],
    alpha2: 'tc',
    countryCode: 796,
    nationality: 'Turks and Caicos Island',
    translations: {he: 'איי טורקס וקאיקוס', fr: '', es: ''},
    pluralNation: {es: 'turcocaiqueños'},
  },
  {
    name: 'Tuvalu',
    synonyms: [],
    alpha2: 'tv',
    countryCode: 798,
    nationality: 'Tuvaluan',
    translations: {he: 'טובאלו', fr: 'Tuvalu', es: ''},
    pluralNation: {en: 'Tuvaluans', fr: 'Tuvaluans', es: 'Tuvaluanos'},
  },
  {
    name: 'Uganda',
    synonyms: [],
    alpha2: 'ug',
    countryCode: 800,
    nationality: 'Ugandan',
    translations: {he: 'אוגנדה', fr: 'Ouganda', es: ''},
    pluralNation: {
      en: 'Ugandans',
      he: 'אוגנדים',
      fr: 'Ougandais',
      es: 'ugandéses',
    },
  },
  {
    name: 'Ukraine',
    synonyms: [],
    alpha2: 'ua',
    countryCode: 804,
    nationality: 'Ukrainian',
    translations: {he: 'אוקראינה', fr: '', es: 'Ucrania'},
    pluralNation: {
      en: 'Ukrainians',
      he: 'אוקראינים',
      fr: 'Ukrainiens',
      es: 'Ucranianos',
    },
  },
  {
    name: 'United Arab Emirates',
    synonyms: ['Emirati'],
    alpha2: 'ae',
    countryCode: 784,
    nationality: 'Emirati, Emirian, Emiri',
    translations: {
      he: 'איחוד האמירויות',
      fr: 'Émirats arabes unis',
      es: 'Emiratos Árabes Unidos',
    },
    pluralNation: {en: 'Emiratis', he: 'אמירתיים', fr: 'Émiratis'},
  },
  {
    name: 'United Kingdom',
    synonyms: [
      'UK',
      'England',
      'Scotland',
      'U.K.',
      'אנגליה',
      'בריטניה',
      'Grande-Bretagne',
      'Angleterre',
    ],
    alpha2: 'gb',
    countryCode: 826,
    nationality: 'British, UK',
    translations: {
      he: 'בריטניה',
      fr: "Royaume-Uni de Grande-Bretagne et dֿ'Irlande du Nord ",
      es: 'Reino Unido de Gran Bretaña e Irlanda del Norte',
    },
    pluralNation: {en: 'British', he: 'בריטים', fr: 'Britanniques'},
  },
  {
    name: 'USA',
    synonyms: [
      'USA',
      'US',
      'U.S.A',
      'United States',
      'ארצות הברית',
      'ארה״ב',
      'ארהב',
      'אמריקה',
      'U.S.',
      'Etats-Unis',
      'E.U',
      'USA. EUA',
      'EEUU',
    ],
    alpha2: 'us',
    countryCode: 840,
    nationality: 'American',
    translations: {
      he: 'ארצות הברית',
      fr: "États-Unis d'Amérique",
      es: 'Estados Unidos de América',
    },
    pluralNation: {
      en: 'Americans',
      he: 'אמריקנים',
      fr: 'Américains',
      es: 'estadounidenses',
    },
  },
  {
    name: 'Uruguay',
    synonyms: [],
    alpha2: 'uy',
    countryCode: 858,
    nationality: 'Uruguayan',
    translations: {he: 'אורוגוואי', fr: '', es: ''},
    pluralNation: {
      en: 'Uruguayans',
      he: 'אורוגוואים',
      fr: 'Uruguayens',
      es: 'uruguayos',
    },
  },
  {
    name: 'Uzbekistan',
    synonyms: [],
    alpha2: 'uz',
    countryCode: 860,
    nationality: 'Uzbekistani, Uzbek',
    translations: {he: 'אוזבקיסטן', fr: 'Ouzbékistan', es: 'Uzbekistán'},
    pluralNation: {en: 'Uzbeks', he: 'אוזבקים', fr: 'Ouzbeks', es: 'Uzbecos'},
  },
  {
    name: 'Vanuatu',
    synonyms: [],
    alpha2: 'vu',
    countryCode: 548,
    nationality: 'Ni-Vanuatu, Vanuatuan',
    translations: {he: 'ונואטו', fr: '', es: ''},
    pluralNation: {en: 'Vanuatuans', fr: 'Vanuatuans', es: 'Vanuatuenses'},
  },
  {
    name: 'Venezuela',
    synonyms: ['República Bolivariana de Venezuela', 'Rep de Venezuela', 'Ven'],
    alpha2: 've',
    countryCode: 862,
    nationality: 'Venezuelan',
    translations: {
      he: 'ונצואלה',
      fr: 'Venezuela (République bolivarienne du)',
      es: 'Venezuela (República Bolivariana de)',
    },
    pluralNation: {
      en: 'Venezuelans',
      he: 'ונצואלים',
      fr: 'Vénézuéliens',
      es: 'Venezolanos',
    },
  },
  {
    name: 'Viet Nam',
    synonyms: [],
    alpha2: 'vn',
    countryCode: 704,
    nationality: 'Vietnamese',
    translations: {he: 'ויאטנאם', fr: '', es: ''},
    pluralNation: {
      en: 'Vietnamese',
      he: 'ויאטנאמים',
      fr: 'Vietnamiens',
      es: 'vietnamitas',
    },
  },
  {
    name: 'Virgin Islands (British)',
    synonyms: [],
    alpha2: 'vg',
    countryCode: 92,
    nationality: 'British Virgin Island',
    translations: {he: 'איי הבתולה הבריטיים', fr: '', es: ''},
    pluralNation: {en: 'Virgin Islanders', es: 'Virgenense británicos'},
  },
  {
    name: 'Virgin Islands (U.S.)',
    synonyms: [],
    alpha2: 'vi',
    countryCode: 850,
    nationality: 'U.S. Virgin Island',
    translations: {he: 'איי הבתולה של ארצות הברית', fr: '', es: ''},
    pluralNation: {en: 'Virgin Islanders', es: 'virgenenses'},
  },
  {
    name: 'Wallis and Futuna',
    synonyms: [],
    alpha2: 'wf',
    countryCode: 876,
    nationality: 'Wallis and Futuna, Wallisian or Futunan',
    translations: {he: 'ואליס ופוטונה', fr: '', es: ''},
    pluralNation: {es: 'Walisianos'},
  },
  {
    name: 'Western Sahara',
    synonyms: [],
    alpha2: 'eh',
    countryCode: 732,
    nationality: 'Sahrawi, Sahrawian, Sahraouian',
    translations: {he: 'סהרה המערבית', fr: '', es: ''},
    pluralNation: {},
  },
  {
    name: 'Yemen',
    synonyms: [],
    alpha2: 'ye',
    countryCode: 887,
    nationality: 'Yemeni',
    translations: {he: 'תימן', fr: 'Yémen', es: ''},
    pluralNation: {en: 'Yemenis', he: 'תימנים', fr: 'Yéménites', es: 'yemenís'},
  },
  {
    name: 'Zambia',
    synonyms: [],
    alpha2: 'zm',
    countryCode: 894,
    nationality: 'Zambian',
    translations: {he: 'זמביה', fr: 'Zambie', es: ''},
    pluralNation: {
      en: 'Zambians',
      he: 'זמבים',
      fr: 'Zambiens',
      es: 'Zambianos',
    },
  },
  {
    name: 'Zimbabwe',
    synonyms: [],
    alpha2: 'zw',
    countryCode: 716,
    nationality: 'Zimbabwean',
    translations: {he: 'זימבבואה', fr: '', es: ''},
    pluralNation: {en: 'Zimbabweans', fr: 'Zimbabwéens', es: 'Zimbabuenses'},
  },
  {
    name: 'Democratic Republic of the Congo',
    synonyms: ['DRC', 'DR Congo', 'Congo-Kinshasa'],
    alpha2: 'cd',
    countryCode: 180,
    nationality: 'Congolese',
    translations: {he: 'הרפובליקה הדמוקרטית של קונגו', fr: '', es: ''},
    pluralNation: {en: 'Congolese', he: 'קונגולזים', fr: 'Congolais'},
  },
];

export const getIconAsset = (country) => {
  if (country) {
    const countryCode = country.alpha2.toLowerCase();
    return `https://assets.homeis.com/image/upload/c_fill,f_jpg,w_100/v1/homeis-prod/assets/country-flags/v3/${countryCode}.png`;
  }
  return null;
};

export const getCountryByCode = (countryCode) =>
  countries.find((country) => country.countryCode === countryCode);

export const getCountryByName = (countryName) =>
  countries.find(
    (country) => country.name.toLowerCase() === countryName.toLowerCase(),
  );

export const getCountryImageByCode = (countryCode) => {
  const selectedCountry = getCountryByCode(countryCode);
  return getIconAsset(selectedCountry);
};

export const getCountryImageByName = (countryName) => {
  const selectedCountry = getCountryByName(countryName);
  return getIconAsset(selectedCountry);
};

export const getTranslatedName = ({countryCode, countryName, language}) => {
  let country;
  if (countryCode) {
    country = getCountryByCode(countryCode);
  }
  if (!country && countryName) {
    country = getCountryByName(countryName);
  }
  return country ? get(country, `translations.${language}`, country.name) : '';
};

export default countries;
